Remove external ADR parsing and publishing
It currently does not work due to
```
Error: Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.structurizr.documentation.DecisionStatus.Approved
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.structurizr.documentation.DecisionStatus.valueOf(DecisionStatus.java:6)
	at com.structurizr.documentation.AdrToolsImporter.extractStatus(AdrToolsImporter.java:153)
	at com.structurizr.documentation.AdrToolsImporter.importArchitectureDecisionRecords(AdrToolsImporter.java:92)
	at uk.gov.justice.hmpps.architecture.PullADRsKt.pullADRs$lambda-1(pullADRs.kt:13)
```

As it's not a reused functionality, just a trial, there's no value in
keeping it when it's breaking the build